"""create locations table

Revision ID: 910153fc1a7a
Revises: 
Create Date: 2025-03-14 17:38:20.560763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910153fc1a7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    locations = op.create_table('locations',
                                sa.Column('id', sa.Integer(), nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.Column('latitude', sa.Float(), nullable=False),
                                sa.Column('longitude', sa.Float(), nullable=False),
                                sa.PrimaryKeyConstraint('id')
                                )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(
            locations,
            [
                {'id': 1, 'name': 'New York', 'latitude': 40.712776, 'longitude': -74.005974},
                {'id': 2, 'name': 'Los Angeles', 'latitude': 34.052235, 'longitude': -118.243683},
                {'id': 3, 'name': 'Paris', 'latitude': 41.878113, 'longitude': -87.629799}
            ]
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###

